name = "MLJTestIntegration"
uuid = "697918b4-fdc1-4f9e-8ff9-929724cee270"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.2.0"

[deps]
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJTuning = "03970b2e-30c4-11ea-3135-d1576263f10f"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MLJ = "0.18"
julia = "1.6"
